### ISSUE TITLE
Request for Vapor 4.5.1 compatibility  

### ISSUE THREAD

**Issue by msafder** [nerdsupremacist/GraphZahl#19]
The current HelloWorld example doesn't work with Vapor 4.5.1

```swift
// Create a GraphQLSchema
enum HelloWorld: GraphQLSchema {

    // Describe the Query Type
    class Query: QueryType {
        func greeting(name: String) -> String {
            return "Hello, \(name)"
        }
    }

    typealias Mutation = None
}
```
I tried changing to below and it builds but not sure this the correct solution?

```swift
enum HelloWorld: GraphQLSchema {
  
  class Query: QueryType {
    
    required init(viewerContext: ()) {
      
    }
    
    func greeting(name: String) -> String {
      return "Hello, \(name)"
    }
  }
}
```
Would LOVE to try out this library with Vapor 4.5.1. But, I'm getting a ': dependency 'graphzahl-vapor-support' is not used by any target' warning when I add 'graphzahl-vapor-support' to my SwiftPM and doesn't seem to be bringing in the extensions.  Any ideas? 

Cheers!

**Comment by nerdsupremacist** [comment]
Hey!

Yes I removed the 

```
required init(viewerContext: ()) {}
```

From the README examples because it clutters the example and doesn't really help us understand how it works. Leaving it empty is fine.

I can't tell you with 100% certainty what is going on. But my best guess is that you're using the string "graphzahl-vapor-support" when adding the dependency target to your apps target. The actual name of the dependency target is "GraphZahlVaporSupport"

Here is an example where Vapor support is used. In case you want to look around a bit more: https://github.com/nerdsupremacist/tmdb

**Comment by nerdsupremacist** [comment]
But I hadn't noticed that vapor was already out of Beta. 
GraphZahlVaporSupport Is probably a bit out of date

**Comment by msafder** [comment]
This is SOOOOOOO KOOL! The tmdb sample app is exactly what I needed to help get my head around GraphZahl. Getting hands dirty now...excellent work thanks!

**Comment by nerdsupremacist** [comment]
I just updated GraphZahlVaporSupport to use non-beta Vapor
